class Constants:
    SERVE_LEFT = 0
    HIT_LEFT_TABLE_AFTER_SERVE = 1

    SERVE_RIGHT = 2
    HIT_RIGHT_TABLE_AFTER_SERVE = 3

    NET_FROM_LEFT = 4
    NET_FROM_RIGHT = 5

    HIT_RIGHT_TABLE = 6
    HIT_LEFT_TABLE = 7

    BLOCKED_FROM_RIGHT = 8
    BLOCKED_FROM_LEFT = 9

    OUT_FROM_LEFT = 10
    OUT_FROM_RIGHT = 11

    RIGHT = 0
    LEFT = 1
